-- MySQL Script generated by MySQL Workbench
-- Wed Jan 30 14:44:05 2019
-- Model: bibliothek    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliothek
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bibliothek` ;

-- -----------------------------------------------------
-- Schema bibliothek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliothek` DEFAULT CHARACTER SET utf8 ;
USE `bibliothek` ;

-- -----------------------------------------------------
-- Table `bibliothek`.`verlag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliothek`.`verlag` ;

CREATE TABLE IF NOT EXISTS `bibliothek`.`verlag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `webseite` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Name_UNIQUE` ON `bibliothek`.`verlag` (`name` ASC);

CREATE UNIQUE INDEX `Webseite_UNIQUE` ON `bibliothek`.`verlag` (`webseite` ASC);


-- -----------------------------------------------------
-- Table `bibliothek`.`land`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliothek`.`land` ;

CREATE TABLE IF NOT EXISTS `bibliothek`.`land` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bezeichnung` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Bezeichnung_UNIQUE` ON `bibliothek`.`land` (`bezeichnung` ASC);


-- -----------------------------------------------------
-- Table `bibliothek`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliothek`.`autor` ;

CREATE TABLE IF NOT EXISTS `bibliothek`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vorname` VARCHAR(45) NOT NULL,
  `nachname` VARCHAR(45) NOT NULL,
  `geburtsdatum` DATE NOT NULL,
  `e_mail` VARCHAR(45) NULL,
  `land_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_autor_land1`
    FOREIGN KEY (`land_id`)
    REFERENCES `bibliothek`.`land` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_autor_land1_idx` ON `bibliothek`.`autor` (`land_id` ASC);

CREATE UNIQUE INDEX `e_mail_UNIQUE` ON `bibliothek`.`autor` (`e_mail` ASC);


-- -----------------------------------------------------
-- Table `bibliothek`.`kategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliothek`.`kategorie` ;

CREATE TABLE IF NOT EXISTS `bibliothek`.`kategorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `kat_name_UNIQUE` ON `bibliothek`.`kategorie` (`name` ASC);


-- -----------------------------------------------------
-- Table `bibliothek`.`buch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliothek`.`buch` ;

CREATE TABLE IF NOT EXISTS `bibliothek`.`buch` (
  `isbn` VARCHAR(30) NOT NULL,
  `titel` VARCHAR(45) NOT NULL,
  `kurzbeschreibung` BLOB NOT NULL,
  `erscheinungsjahr` INT NOT NULL,
  `auflage` INT NOT NULL,
  `ver_id` INT NOT NULL,
  `aut_id` INT NOT NULL,
  `kat_id` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  CONSTRAINT `fk_buch_verlag`
    FOREIGN KEY (`ver_id`)
    REFERENCES `bibliothek`.`verlag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buch_autor1`
    FOREIGN KEY (`aut_id`)
    REFERENCES `bibliothek`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buch_kategorie1`
    FOREIGN KEY (`kat_id`)
    REFERENCES `bibliothek`.`kategorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_buch_verlag_idx` ON `bibliothek`.`buch` (`ver_id` ASC);

CREATE INDEX `fk_buch_autor1_idx` ON `bibliothek`.`buch` (`aut_id` ASC);

CREATE INDEX `fk_buch_kategorie1_idx` ON `bibliothek`.`buch` (`kat_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bibliothek`.`verlag`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibliothek`;
INSERT INTO `bibliothek`.`verlag` (`id`, `name`, `webseite`) VALUES (DEFAULT, 'Rowohlt Taschenbuch ', 'https://www.rowohlt.de/');
INSERT INTO `bibliothek`.`verlag` (`id`, `name`, `webseite`) VALUES (DEFAULT, 'Suhrkamp Verlag', 'https://www.suhrkamp.de/');
INSERT INTO `bibliothek`.`verlag` (`id`, `name`, `webseite`) VALUES (DEFAULT, 'Fischer Verlag', 'https://www.fischerverlage.de/');
INSERT INTO `bibliothek`.`verlag` (`id`, `name`, `webseite`) VALUES (DEFAULT, 'Éditions Gallimard', 'http://www.gallimard.fr/');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bibliothek`.`land`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibliothek`;
INSERT INTO `bibliothek`.`land` (`id`, `bezeichnung`) VALUES (DEFAULT, 'Frankreich');
INSERT INTO `bibliothek`.`land` (`id`, `bezeichnung`) VALUES (DEFAULT, 'Deutschland');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bibliothek`.`autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibliothek`;
INSERT INTO `bibliothek`.`autor` (`id`, `vorname`, `nachname`, `geburtsdatum`, `e_mail`, `land_id`) VALUES (DEFAULT, 'Albert', 'Camus', '1913.11.07', NULL, 1);
INSERT INTO `bibliothek`.`autor` (`id`, `vorname`, `nachname`, `geburtsdatum`, `e_mail`, `land_id`) VALUES (DEFAULT, 'Marcel', 'Proust', '1871.07.10', NULL, 1);
INSERT INTO `bibliothek`.`autor` (`id`, `vorname`, `nachname`, `geburtsdatum`, `e_mail`, `land_id`) VALUES (DEFAULT, 'Franz', 'Kafka', '1883.07.03', NULL, 2);
INSERT INTO `bibliothek`.`autor` (`id`, `vorname`, `nachname`, `geburtsdatum`, `e_mail`, `land_id`) VALUES (DEFAULT, 'Antoine', 'de Saint-Exupéry', '1900.06.29', NULL, 1);
INSERT INTO `bibliothek`.`autor` (`id`, `vorname`, `nachname`, `geburtsdatum`, `e_mail`, `land_id`) VALUES (DEFAULT, 'André', 'Malraux', '1901.11.03', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bibliothek`.`kategorie`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibliothek`;
INSERT INTO `bibliothek`.`kategorie` (`id`, `name`) VALUES (DEFAULT, 'Krimi');
INSERT INTO `bibliothek`.`kategorie` (`id`, `name`) VALUES (DEFAULT, 'Roman');
INSERT INTO `bibliothek`.`kategorie` (`id`, `name`) VALUES (DEFAULT, 'Fabel');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bibliothek`.`buch`
-- -----------------------------------------------------
START TRANSACTION;
USE `bibliothek`;
INSERT INTO `bibliothek`.`buch` (`isbn`, `titel`, `kurzbeschreibung`, `erscheinungsjahr`, `auflage`, `ver_id`, `aut_id`, `kat_id`) VALUES ('978-3-86680-192-9', 'Der Fremde', 0x44696520476573636869636874652064657320736F7A696F7061746869736368206475726368206469652057656C742073746F6C7065726E64656E204D6575727361756C742C2064657220756E62657465696C6967742064656E20546F6420646572204D757474657220736368696C6465727420756E64207370C3A47465722064696520417566726567756E6720756D207365696E656E204D6F7264206E696368742076657273746568742E, 1942, 20, 1, 1, 1);
INSERT INTO `bibliothek`.`buch` (`isbn`, `titel`, `kurzbeschreibung`, `erscheinungsjahr`, `auflage`, `ver_id`, `aut_id`, `kat_id`) VALUES ('978-3-12-732320-7', 'Auf der Suche nach der verlorenen Zeit', 0x4461732061646C69676520756E642067726FC39F62C3BC726765726C69636865204672616E6B72656963682064657220766F726C65747A74656E204A61687268756E6465727477656E6465207A7769736368656E2045726F74696B20756E64204C616E67657765696C652E, 1913, 42, 2, 2, 2);
INSERT INTO `bibliothek`.`buch` (`isbn`, `titel`, `kurzbeschreibung`, `erscheinungsjahr`, `auflage`, `ver_id`, `aut_id`, `kat_id`) VALUES ('978-3-7657-2781-8', 'Der Prozess', 0x4A6F736566204B2E2C206772756E646C6F732076657268616674657420756E6420676566616E67656E20696E2065696E656D20616C70747261756D68616674656E204E65747A206175732073656C62737462657AC3BC676C696368656E2047657365747A656E20756E642062C3BC726F6B72617469736368656E20537472756B747572656E20E2809320646572204B6C617373696B657220646572205374616174736B726974696B2E, 1925, 62, 3, 3, 2);
INSERT INTO `bibliothek`.`buch` (`isbn`, `titel`, `kurzbeschreibung`, `erscheinungsjahr`, `auflage`, `ver_id`, `aut_id`, `kat_id`) VALUES ('3-86680-192-0', 'Der kleine Prinz', 0x446572206B6C65696E65205072696E7A20657266C3BC6C6C74206D697420616C6C7A752065696E66616368656E205761687268656974656E20646965205365686E737563687420646573206D6F6465726E656E204D656E736368656E206E616368206B6C6172656E20416E74776F7274656E20696E2065696E6572206B6F6D706C657865722077657264656E64656E2057656C742E204E6168657A75203930204D696C6C696F6E656E204D616C207665726B6175667420756E642064616D69742065696E657320646572206572666F6C6772656963687374656E2042C3BC6368657220616C6C6572205A656974656E20286162657220656865722065696E2042C3BC63686C65696E292E, 1943, 25, 4, 4, 3);
INSERT INTO `bibliothek`.`buch` (`isbn`, `titel`, `kurzbeschreibung`, `erscheinungsjahr`, `auflage`, `ver_id`, `aut_id`, `kat_id`) VALUES ('3-680-08783-7', 'So lebt der Mensch', 0x44696520676573636865697465727465206B6F6D6D756E6973746973636865205265766F6C7574696F6E206465732031322E20417072696C203139323720696E205368616E6768616920756E64206968726520466F6C67656E2066C3BC722065696E6661636865204D656E736368656E2E, 1933, 70, 1, 5, 2);

COMMIT;

